export let data = [
    {
        img : './media/amur.png',
        autor : 'Марсель Руссо',
        name : 'Охота Амура',
        material : 'Холст, масло (50х80)',
        price : '14 500 руб',
        country: 'france',
    },
    {
        img : './media/with-dog.png',
        autor : 'Анри Селин',
        name : 'Дама с собачкой',
        material : 'Акрил, бумага (50х80)',
        price : '16 500 руб',
        country: 'france',
    },
    {
        img : './media/process.png',
        autor : 'Франсуа Дюпон',
        name : 'Процедура',
        material : 'Цветная литография (40х60)',
        price : '20 000 руб',
        country: 'france',
    },
    {
        img : './media/rose.png',
        autor : 'Луи Детуш',
        name : 'Роза',
        material : 'Бумага, акрил (50х80)',
        price : '12 000 руб',
        country: 'france',
    },
    {
        img : './media/birds.png',
        autor : 'Франсуа Дюпон',
        name : 'Птичья трапеза',
        material : 'Цветная литография (40х60)',
        price : '22 500 руб',
        country: 'france',
    },
    {
        img : './media/beach.jpg',
        autor : 'Пьер Моранж',
        name : 'Пейзаж с рыбой',
        material : 'Цветная литография (40х60)',
        price : '20 000 руб',
        country: 'france',
    },
    {
        img : './media/under-city.png',
        autor : 'Курт Вернер',
        name : 'Над городом',
        material : 'Цветная литография (40х60)',
        price : '16 000 руб',
        country: 'germany',
    },
    {
        img : './media/litel-birds.png',
        autor : 'Макс Рихтер',
        name : 'Птенцы',
        material : 'Холст, масло (50х80)',
        price : '14 500 руб',
        country: 'germany',
    },
    {
        img : './media/among.png',
        autor : 'Мартин майнер',
        name : 'Среди листьев',
        material : 'Цветная литография (40х60)',
        price : '20 000 руб',
        country: 'germany',
    },
    {
        img : './media/bright.png',
        autor : 'Герман Беккер',
        name : 'Яркая птица',
        material : 'Цветная литография (40х60)',
        price : '13 000 руб',
        country: 'germany',
    },
    {
        img : './media/birds2.png',
        autor : 'Вульф Бауэр',
        name : 'Дятлы',
        material : 'Бумага, акрил (50х80)',
        price : '20 000 руб',
        country: 'germany',
    },
    {
        img : './media/grate.png',
        autor : 'Вальтер Хартманн',
        name : 'Большие воды',
        material : 'Бумага, акрил (50х80)',
        price : '23 000 руб',
        country: 'germany',
    },
    {
        img : './media/muse.png',
        autor : 'Пол Смит',
        name : 'Дикий зверь',
        material : 'Акварель, бумага (50х80)',
        price : '19 500 руб',
        country: 'england',
    },
    {
        img : './media/clif.png',
        autor : 'Джон Уайт',
        name : 'Скалистый берег',
        material : 'Цветная литография (40х60)',
        price : '17 500 руб',
        country: 'england',
    },
    {
        img : './media/river.png',
        autor : 'Джим Уотсон',
        name : 'Река и горы',
        material : 'Акварель, бумага (50х80)',
        price : '14 500 руб',
        country: 'england',
    },
    {
        img : './media/bird3.png',
        autor : 'Юджин Зиллион',
        name : 'Белый попугай',
        material : 'Цветная литография (40х60)',
        price : '15 500 руб',
        country: 'england',
    },
    {
        img : './media/fish.png',
        autor : 'Эрик Гиллман',
        name : 'Ночная рыба',
        material : 'Бумага, акрил (50х80)',
        price : '12 500 руб',
        country: 'england',
    },
    {
        img : './media/cat.png',
        autor : 'Альфред Барр',
        name : 'Рыжий кот',
        material : 'Цветная литография (40х60)',
        price : '21 000 руб',
        country: 'england',
    },
]